# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChatgptTui < Formula
  desc ""
  homepage "https://github.com/tearingItUp786/chatgpt-tui"
  version "0.2.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tearingItUp786/chatgpt-tui/releases/download/v0.2.0/chatgpt-tui_0.2.0_darwin_arm64.zip"
      sha256 "698d950153c7e068afe5aef6ca5db59604ce794543e9fe45cc7569e7a2ddb824"

      def install
        bin.install "chatgpt-tui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tearingItUp786/chatgpt-tui/releases/download/v0.2.0/chatgpt-tui_0.2.0_darwin_amd64.zip"
      sha256 "d6edd9e6a0a9ea454285e61f0db8fdd6502ab5551771cbc4c4984b66cecf17fe"

      def install
        bin.install "chatgpt-tui"
      end
    end
  end
end
