# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChatgptTui < Formula
  desc ""
  homepage "https://github.com/tearingItUp786/chatgpt-tui"
  version "0.1.11"
  depends_on :macos

  on_macos do
    url "https://github.com/tearingItUp786/chatgpt-tui/releases/download/v0.1.11/chatgpt-tui_0.1.11_darwin_amd64.zip"
    sha256 "0f420061196285af19a0b59a701ce10e4c458aa80231419f2fd5a21b5c6d269e"

    def install
      bin.install "golang"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the ChatgptTui
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end
end
