# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nekot < Formula
  desc ""
  homepage "https://github.com/tearingItUp786/chatgpt-tui"
  version "0.5.9"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/tearingItUp786/chatgpt-tui/releases/download/v0.5.9/nekot_0.5.9_darwin_arm64.zip"
    sha256 "00d007366178a4da5a31490e89f200861f36a81766087db544e909b483f30a16"

    def install
      bin.install "bin/nekot"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/tearingItUp786/chatgpt-tui/releases/download/v0.5.9/nekot_0.5.9_darwin_amd64.zip"
    sha256 "107f760ce98352707d59d7beaac09c8263fbba83f1ff9cdc839e4ebd980903ca"

    def install
      bin.install "bin/nekot"
    end
  end
end
