# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nekot < Formula
  desc ""
  homepage "https://github.com/tearingItUp786/chatgpt-tui"
  version "0.6.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/tearingItUp786/nekot/releases/download/v0.6.0/nekot_0.6.0_darwin_arm64.zip"
    sha256 "67ed2c35420595863351152850c6d94e1f39e0921ca20d90583744cce332800f"

    def install
      bin.install "bin/nekot"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/tearingItUp786/nekot/releases/download/v0.6.0/nekot_0.6.0_darwin_amd64.zip"
    sha256 "0649980d313688f16cdfb6281c6d4ea3addb066511eadb061677e477c50b6094"

    def install
      bin.install "bin/nekot"
    end
  end
end
