# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nekot < Formula
  desc ""
  homepage "https://github.com/tearingItUp786/chatgpt-tui"
  version "0.5.11"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/tearingItUp786/chatgpt-tui/releases/download/v0.5.11/nekot_0.5.11_darwin_arm64.zip"
    sha256 "3abd56e5101443a4f4b2b842e7a78ece38e7ec7980935f52de47de96aab7cac2"

    def install
      bin.install "bin/nekot"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/tearingItUp786/chatgpt-tui/releases/download/v0.5.11/nekot_0.5.11_darwin_amd64.zip"
    sha256 "06863fe82771d8fcd3f7df70eabeb9003a4a59cd24d42ce16c71b7fdd8da5e8d"

    def install
      bin.install "bin/nekot"
    end
  end
end
