# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RcNekot < Formula
  desc ""
  homepage "https://github.com/tearingItUp786/chatgpt-tui"
  version "0.5.12-rc2"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/tearingItUp786/chatgpt-tui/releases/download/v0.5.12-rc2/rc-nekot_chatgpt-tui_0.5.12-rc2_darwin_arm64.zip"
    sha256 "ce7ece1d039675cea2ac62a22db11cf3cbc229420952d7b4d84ed57742578220"

    def install
      bin.install "bin/rc-nekot"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/tearingItUp786/chatgpt-tui/releases/download/v0.5.12-rc2/rc-nekot_chatgpt-tui_0.5.12-rc2_darwin_amd64.zip"
    sha256 "67fc72fa4abcca215b429c9a2b01a662887c9235705c8074e122ff172a42c5ff"

    def install
      bin.install "bin/rc-nekot"
    end
  end
end
